### ISSUE TITLE
Error: "Call to a member function getBoots() on null" (EXCEPTION) in "PiggyCustomEnchants_dev-182.phar/src/PiggyCustomEnchants/EventListener" at line 1362

### ISSUE THREAD

**Issue by teracube** [DaPigGuy/PiggyCustomEnchants#107] opened 2018-01-04 06:31 UTC
Please make sure your issue complies with these guidelines:
- * [X] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [X] Issue must have not been reported previously
- * [X] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [X] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [X] If possible, provide crashdumps/errors related to the issue.

#### **General**

Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'PiggyCustomEnchants v1.1.0': Call to a member function getBoots() on null on PiggyCustomEnchants\EventListener

Error: "Call to a member function getBoots() on null" (EXCEPTION) in "PiggyCustomEnchants_dev-182.phar/src/PiggyCustomEnchants/EventListener" at line 1362
#### **Version of PiggyCustomEnchants:**

PiggyCustomEnchants_dev-182

#### **Steps to Reproduce the Issue**

sorry i do not know

#### **Extra Information**

```2018-01-03 [18:42:47] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'PiggyCustomEnchants v1.1.0': Call to a member function getBoots() on null on PiggyCustomEnchants\EventListener
2018-01-03 [18:42:47] [Server thread/CRITICAL]: Error: "Call to a member function getBoots() on null" (EXCEPTION) in "PiggyCustomEnchants_dev-182.phar/src/PiggyCustomEnchants/EventListener" at line 1362
2018-01-03 [18:42:47] [Server thread/DEBUG]: #0 PiggyCustomEnchants_dev-182.phar/src/PiggyCustomEnchants/EventListener(394): PiggyCustomEnchants\EventListener->checkArmorEnchants(pocketmine\Player object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): PiggyCustomEnchants\EventListener->onDataPacketReceive(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(PiggyCustomEnchants\EventListener object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(721): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(91): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\PlayerActionPacket object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #7 src/pocketmine/Player(2969): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #9 vendor/pmmp/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 77.xxx.225.37:47357, raklib\protocol\EncapsulatedPacket object, integer 0)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/RakLibInterface(82): raklib\server\ServerHandler->handlePacket()
2018-01-03 [18:42:47] [Server thread/DEBUG]: #11 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
2018-01-03 [18:42:47] [Server thread/DEBUG]: #12 src/pocketmine/Server(2524): pocketmine\network\Network->processInterfaces()
2018-01-03 [18:42:47] [Server thread/DEBUG]: #13 src/pocketmine/Server(2276): pocketmine\Server->tick()
2018-01-03 [18:42:47] [Server thread/DEBUG]: #14 src/pocketmine/Server(2151): pocketmine\Server->tickProcessor()
2018-01-03 [18:42:47] [Server thread/DEBUG]: #15 src/pocketmine/Server(1739): pocketmine\Server->start()
2018-01-03 [18:42:47] [Server thread/DEBUG]: #16 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gsp_1485/g3.hmserv.eu-19144/, string /home/gsp_1485/g3.hmserv.eu-19144/plugins/)
2018-01-03 [18:42:47] [Server thread/DEBUG]: #17 /home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar(1): require(string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/src/pocketmine/PocketMine.php)```
--------------------------

```-
2018-01-03 [20:50:41] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'PiggyCustomEnchants v1.1.0': Call to a member function getBoots() on null on PiggyCustomEnchants\EventListener
2018-01-03 [20:50:41] [Server thread/CRITICAL]: Error: "Call to a member function getBoots() on null" (EXCEPTION) in "PiggyCustomEnchants_dev-182.phar/src/PiggyCustomEnchants/EventListener" at line 1362
2018-01-03 [20:50:41] [Server thread/DEBUG]: #0 PiggyCustomEnchants_dev-182.phar/src/PiggyCustomEnchants/EventListener(394): PiggyCustomEnchants\EventListener->checkArmorEnchants(pocketmine\Player object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): PiggyCustomEnchants\EventListener->onDataPacketReceive(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(PiggyCustomEnchants\EventListener object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(721): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(91): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\PlayerActionPacket object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #7 src/pocketmine/Player(2969): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #9 vendor/pmmp/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 193.xxx.181.136:58650, raklib\protocol\EncapsulatedPacket object, integer 0)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/RakLibInterface(84): raklib\server\ServerHandler->handlePacket()
2018-01-03 [20:50:41] [Server thread/DEBUG]: #11 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
2018-01-03 [20:50:41] [Server thread/DEBUG]: #12 src/pocketmine/Server(2524): pocketmine\network\Network->processInterfaces()
2018-01-03 [20:50:41] [Server thread/DEBUG]: #13 src/pocketmine/Server(2276): pocketmine\Server->tick()
2018-01-03 [20:50:41] [Server thread/DEBUG]: #14 src/pocketmine/Server(2151): pocketmine\Server->tickProcessor()
2018-01-03 [20:50:41] [Server thread/DEBUG]: #15 src/pocketmine/Server(1739): pocketmine\Server->start()
2018-01-03 [20:50:41] [Server thread/DEBUG]: #16 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gsp_1485/g3.hmserv.eu-19144/, string /home/gsp_1485/g3.hmserv.eu-19144/plugins/)
2018-01-03 [20:50:41] [Server thread/DEBUG]: #17 /home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar(1): require(string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/src/pocketmine/PocketMine.php)```

**Comment by DaPigGuy** [comment] 2018-01-04 07:02
Plugin list?

**Comment by teracube** [comment] 2018-01-04 08:44
@DaPigGuy 


all plugins latest commit
Loading MagicWE2 v5.4.3
Loading AllSigns v1.0.5
Loading CustomAlerts v1.7.2-3
Loading essentialsTP v1.2.0-5
Loading BanItem v2.3.2-4
Loading EconomyAPI v5.7.1-4
Loading PiggyCustomEnchants v1.1.0
Loading VoteReward v3.0.2-4
Loading LiveXYZ v0.6.0.4-beta
Loading Worlds v1.0.13
Loading iProtector v3.1.0-9
Loading Slapper v1.3.7
Loading EconomyShop v2.0.8-6
Loading PurePerms v1.4.1-3
Loading EconomySell v2.0.7-4
Loading AlwaysSpawn v2.2.3-4
Loading FactionsPro v1.4.5-9
Loading PureChat v1.4.10-4
Loading GrabBag v2.4.0-5

**Comment by teracube** [comment] 2018-01-04 13:33
@DaPigGuy 

same issue with latest commit ?

PocketMine-MP version 1.7dev-586 "[REDACTED]" (API 3.0.0-ALPHA10)
PiggyCustomEnchants_dev-186.phar 

```2018-01-04 [13:22:50] [Server thread/INFO]: TwistyJamipro[/210.50.xxx.171:44262] logged out due to Kicked by admin. Reason: Flying is not enabled on this server
2018-01-04 [13:22:50] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'PiggyCustomEnchants v1.1.0': Call to a member function getBoots() on null on PiggyCustomEnchants\EventListener
2018-01-04 [13:22:50] [Server thread/CRITICAL]: Error: "Call to a member function getBoots() on null" (EXCEPTION) in "PiggyCustomEnchants_dev-186.phar/src/PiggyCustomEnchants/EventListener" at line 1377
2018-01-04 [13:22:50] [Server thread/DEBUG]: #0 PiggyCustomEnchants_dev-186.phar/src/PiggyCustomEnchants/EventListener(392): PiggyCustomEnchants\EventListener->checkArmorEnchants(pocketmine\Player object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): PiggyCustomEnchants\EventListener->onDataPacketReceive(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(PiggyCustomEnchants\EventListener object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(721): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(91): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\PlayerActionPacket object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #7 src/pocketmine/Player(2969): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #9 vendor/pmmp/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 210.50.xxx.171:44262, raklib\protocol\EncapsulatedPacket object, integer 0)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/RakLibInterface(84): raklib\server\ServerHandler->handlePacket()
2018-01-04 [13:22:50] [Server thread/DEBUG]: #11 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
2018-01-04 [13:22:50] [Server thread/DEBUG]: #12 src/pocketmine/Server(2524): pocketmine\network\Network->processInterfaces()
2018-01-04 [13:22:50] [Server thread/DEBUG]: #13 src/pocketmine/Server(2276): pocketmine\Server->tick()
2018-01-04 [13:22:50] [Server thread/DEBUG]: #14 src/pocketmine/Server(2151): pocketmine\Server->tickProcessor()
2018-01-04 [13:22:50] [Server thread/DEBUG]: #15 src/pocketmine/Server(1739): pocketmine\Server->start()
2018-01-04 [13:22:50] [Server thread/DEBUG]: #16 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gsp_1485/g3.hmserv.eu-19144/, string /home/gsp_1485/g3.hmserv.eu-19144/plugins/)
2018-01-04 [13:22:50] [Server thread/DEBUG]: #17 /home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar(1): require(string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/src/pocketmine/PocketMine.php)```

**Comment by teracube** [comment] 2018-01-26 09:11
another error log

PocketMine-MP version 1.7dev-634 "[REDACTED]" (API 3.0.0-ALPHA10)
PiggyCustomEnchants v1.1.0 =) PiggyCustomEnchants_dev-199.phar


``2018-01-24 [17:26:20] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'PiggyCustomEnchants v1.1.0': Call to a member function getBoots() on null on PiggyCustomEnchants\EventListener
2018-01-24 [17:26:20] [Server thread/CRITICAL]: Error: "Call to a member function getBoots() on null" (EXCEPTION) in "PiggyCustomEnchants_dev-199.phar/src/PiggyCustomEnchants/EventListener" at line 1367
2018-01-24 [17:26:20] [Server thread/DEBUG]: #0 PiggyCustomEnchants_dev-199.phar/src/PiggyCustomEnchants/EventListener(378): PiggyCustomEnchants\EventListener->checkArmorEnchants(pocketmine\Player object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): PiggyCustomEnchants\EventListener->onDataPacketReceive(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(PiggyCustomEnchants\EventListener object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(721): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(91): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\PlayerActionPacket object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #7 src/pocketmine/Player(2968): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/RakLibInterface(150): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #9 vendor/pocketmine/raklib/server/ServerHandler(103): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 86.XXX.222.121:40845, raklib\protocol\EncapsulatedPacket object, integer 0)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/RakLibInterface(89): raklib\server\ServerHandler->handlePacket()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #11 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #12 src/pocketmine/Server(2527): pocketmine\network\Network->processInterfaces()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #13 src/pocketmine/Server(2279): pocketmine\Server->tick()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #14 src/pocketmine/Server(2154): pocketmine\Server->tickProcessor()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #15 src/pocketmine/Server(1742): pocketmine\Server->start()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #16 src/pocketmine/PocketMine(553): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gsp_1485/g3.hmserv.eu-19144/, string /home/gsp_1485/g3.hmserv.eu-19144/plugins/)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #17 /home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar(1): require(string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
2018-01-24 [17:26:20] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'PiggyCustomEnchants v1.1.0': Call to a member function getBoots() on null on PiggyCustomEnchants\EventListener
2018-01-24 [17:26:20] [Server thread/CRITICAL]: Error: "Call to a member function getBoots() on null" (EXCEPTION) in "PiggyCustomEnchants_dev-199.phar/src/PiggyCustomEnchants/EventListener" at line 1367
2018-01-24 [17:26:20] [Server thread/DEBUG]: #0 PiggyCustomEnchants_dev-199.phar/src/PiggyCustomEnchants/EventListener(378): PiggyCustomEnchants\EventListener->checkArmorEnchants(pocketmine\Player object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): PiggyCustomEnchants\EventListener->onDataPacketReceive(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(PiggyCustomEnchants\EventListener object, pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(721): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(91): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\PlayerActionPacket object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #7 src/pocketmine/Player(2968): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/RakLibInterface(150): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #9 vendor/pocketmine/raklib/server/ServerHandler(103): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 86.XXX.222.121:40845, raklib\protocol\EncapsulatedPacket object, integer 0)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/RakLibInterface(89): raklib\server\ServerHandler->handlePacket()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #11 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #12 src/pocketmine/Server(2527): pocketmine\network\Network->processInterfaces()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #13 src/pocketmine/Server(2279): pocketmine\Server->tick()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #14 src/pocketmine/Server(2154): pocketmine\Server->tickProcessor()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #15 src/pocketmine/Server(1742): pocketmine\Server->start()
2018-01-24 [17:26:20] [Server thread/DEBUG]: #16 src/pocketmine/PocketMine(553): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gsp_1485/g3.hmserv.eu-19144/, string /home/gsp_1485/g3.hmserv.eu-19144/plugins/)
2018-01-24 [17:26:20] [Server thread/DEBUG]: #17 /home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar(1): require(string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/src/pocketmine/PocketMine.php)````

**Comment by DaPigGuy** [comment] 2018-01-26 20:17
They are all of the same problem. However, I can't reproduce the issue.

**Comment by DaPigGuy** [comment] 2018-02-07 22:19
Closing until more information is found.

**Closed by DaPigGuy** 2018-02-07 22:19 UTC
Labels: bug, can't reproduce, not enough information
