### ISSUE TITLE
Enchanting issue

### ISSUE THREAD

**Issue by MadDominic22** [DaPigGuy/PiggyCustomEnchants#258] opened 2020-02-19 18:19 UTC
Centoller opened this issue on 16 Jan · 0 comments
Labels
bug
Comments
@Centoller Centoller commented on 16 Jan • 
Please make sure your issue complies with these guidelines:

 Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
 Issue must have not been reported previously
 Make sure you are on the latest version of PMMP & PiggyCustomEnchants
 Have a detailed title, like "CustomEnchants::getName() must be..."
 If possible, provide crashdumps/errors related to the issue.
General
when upgrading to version 2.0.4 it crashes, I suspect it is the jetpack boots
Version:
PiggyCustomEnchants: 2.0.4
PMMP: pocketmine 3.11.1
OS: Linux
Steps to Reproduce the Issue

Greetings! I have an issue with your plugin. When I try to enchant something, using the command (/ce enchant [customenchant] [level]) it gives me "internal server error" and I crash immediately. The only plugins I'm using are yours and DevTools, thank you in advice. 
Sometimes it gives me this error:
TypeError: "json_decode() expects parameter 1 to be string, bool given" (EXCEPTION) in "plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/tasks/CheckDisabledEnchantsTask" at line 37 

Sometimes instead it gives me this error:
Error: "Call to a member function getSize() on array" (EXCEPTION) in "src/pocketmine/item/enchantment/Enchantment" at line 151

**Comment by DaPigGuy** [comment] 2020-02-19 21:03
The issue with the /ce command may be caused by missing virions (Commando & FormAPI). Please provide an error if not resolved. The second error will be fixed later & the third error is caused by an outdated version of PiggyCE.

**Comment by DaPigGuy** [comment] 2020-02-19 21:06
Second error should now be fixed with commit 04475246752c9d35504f7c0e1cc5de53790c9f92

**Closed** 2020-02-20 16:07 UTC
Labels: bug, not enough information
