### ISSUE TITLE
Overload Enchant causes Internal Server Error

### ISSUE THREAD

**Issue by notacoderr** [DaPigGuy/PiggyCustomEnchants#284] opened 2020-04-14 19:24 UTC
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title (i.e "Poison enchant does not apply effect")

### Issue Description

- Expected result: Overload is supposed to give us more health
- Actual result: Overload causes internal server error.

#### Steps to Reproduce the Issue
1. Enchant any armor with overload
2. Take some damage (to update your health) or rejoin the server

### OS and Versions

* PocketMine-MP: 3.11.6
* PiggyCustomEnchants: v2.1.3
* PHP: 7.2
* Server OS: Ubuntu

[19:18:31] [Server thread/CRITICAL]: InvalidArgumentException: "Maximum -4 is less than the minimum 0" (EXCEPTION) in "src/pocketmine/entity/Attribute" at line 153
[19:18:31] [Server thread/DEBUG]: #0 src/pocketmine/entity/Living(158): pocketmine\entity\Attribute->setMaxValue(double -4)
[19:18:31] [Server thread/DEBUG]: #1 plugins/PiggyCustomEnchants_dev-437.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/armor/OverloadEnchant(34): pocketmine\entity\Living->setMaxHealth(integer -4)
[19:18:31] [Server thread/DEBUG]: #2 plugins/PiggyCustomEnchants_dev-437.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/traits/ToggleTrait(43): DaPigGuy\PiggyCustomEnchants\enchants\armor\OverloadEnchant->toggle(object pocketmine\Player, object pocketmine\item\DiamondBoots, object pocketmine\inventory\ArmorInventory, integer 3, integer 3, boolean )
[19:18:31] [Server thread/DEBUG]: #3 plugins/PiggyCustomEnchants_dev-437.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/traits/ToggleTrait(83): DaPigGuy\PiggyCustomEnchants\enchants\ToggleableEnchantment->onToggle(object pocketmine\Player, object pocketmine\item\DiamondBoots, object pocketmine\inventory\ArmorInventory, integer 3, integer 3, boolean )
[19:18:31] [Server thread/DEBUG]: #4 plugins/PiggyCustomEnchants_dev-437.phar/src/DaPigGuy/PiggyCustomEnchants/EventListener(119): DaPigGuy\PiggyCustomEnchants\enchants\ToggleableEnchantment::attemptToggle(object pocketmine\Player, object pocketmine\item\DiamondBoots, object pocketmine\item\enchantment\EnchantmentInstance, object pocketmine\inventory\ArmorInventory, integer 3, boolean )

**Comment by DaPigGuy** [comment] 2020-04-14 21:18
Duplicate of #283

**Comment by DaPigGuy** [comment] 2020-04-14 21:18
Do you have any idea on how to reproduce the issue?

**Comment by ZaXtha** [comment] 2020-04-14 23:13
Same problem

**Comment by Aericio** [comment] 2020-04-16 06:22
Further conversation in #283 instead

**Closed by Aericio** 2020-04-16 06:22 UTC
Labels: Resolution: Duplicate, Type: Bug
